FROM nvidia/cuda:10.0-cudnn7-runtime
RUN apt update && \
    apt install -y bash \
                   build-essential \
                   curl \
                   wget \
                   python3 \
                   python3-pip \
                   ca-certificates \
                   software-properties-common && \
    rm -rf /var/lib/apt/lists
RUN ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip
RUN python -m pip install --no-cache-dir --upgrade pip && \
    python -m pip install --no-cache-dir \
    nltk==3.4.5 \
    numpy==1.18.2 \
    regex==2020.5.14 \
    torch==1.4.0 \
    tokenizers==0.5.2 \
    transformers==2.7.0 \
    tqdm==4.46.0 \
RUN python -c "import nltk; nltk.download('punkt')"
RUN mkdir -p /tmp/ilm/eval_repro/data
RUN mkdir -p /tmp/ilm/eval_repro/models/abs_ilm
RUN mkdir -p /tmp/ilm/eval_repro/models/abs_ilmscratch
RUN mkdir -p /tmp/ilm/eval_repro/models/abs_lm
RUN mkdir -p /tmp/ilm/eval_repro/models/abs_lmall
RUN mkdir -p /tmp/ilm/eval_repro/models/abs_lmallscratch
RUN mkdir -p /tmp/ilm/eval_repro/models/abs_lmrev
RUN mkdir -p /tmp/ilm/eval_repro/models/abs_lmrevscratch
RUN mkdir -p /tmp/ilm/eval_repro/models/abs_lmscratch
RUN mkdir -p /tmp/ilm/eval_repro/models/lyr_ilm
RUN mkdir -p /tmp/ilm/eval_repro/models/lyr_ilmscratch
RUN mkdir -p /tmp/ilm/eval_repro/models/lyr_lm
RUN mkdir -p /tmp/ilm/eval_repro/models/lyr_lmall
RUN mkdir -p /tmp/ilm/eval_repro/models/lyr_lmallscratch
RUN mkdir -p /tmp/ilm/eval_repro/models/lyr_lmrev
RUN mkdir -p /tmp/ilm/eval_repro/models/lyr_lmrevscratch
RUN mkdir -p /tmp/ilm/eval_repro/models/lyr_lmscratch
RUN mkdir -p /tmp/ilm/eval_repro/models/sto_ilm
RUN mkdir -p /tmp/ilm/eval_repro/models/sto_ilmscratch
RUN mkdir -p /tmp/ilm/eval_repro/models/sto_lm
RUN mkdir -p /tmp/ilm/eval_repro/models/sto_lmall
RUN mkdir -p /tmp/ilm/eval_repro/models/sto_lmallscratch
RUN mkdir -p /tmp/ilm/eval_repro/models/sto_lmrev
RUN mkdir -p /tmp/ilm/eval_repro/models/sto_lmrevscratch
RUN mkdir -p /tmp/ilm/eval_repro/models/sto_lmscratch
RUN mkdir -p /tmp/ilm/train_repro/data
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-FGKu-bodqOsCGrFCYY6Yyp2rTk2rRpc' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1-FGKu-bodqOsCGrFCYY6Yyp2rTk2rRpc" -O /tmp/ilm/eval_repro/models/sto_lm/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=103Cw2ZSb5g5PlTKslmbmhqCaxn3N65OO' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=103Cw2ZSb5g5PlTKslmbmhqCaxn3N65OO" -O /tmp/ilm/eval_repro/models/abs_lmscratch/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=10ScpFR8sG3Ur0WpWdkPYxAsT94jNNmZh' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=10ScpFR8sG3Ur0WpWdkPYxAsT94jNNmZh" -O /tmp/ilm/eval_repro/data/lyr_paragraph_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=14BFLWSaPi2JSsKsa68lcTSnCOnYV9jPm' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=14BFLWSaPi2JSsKsa68lcTSnCOnYV9jPm" -O /tmp/ilm/eval_repro/models/sto_ilmscratch/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=178joxkympgzDwZoExnalWujRq2Jv_37P' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=178joxkympgzDwZoExnalWujRq2Jv_37P" -O /tmp/ilm/eval_repro/data/sto_word_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=18JYIBOtDfnksZPl4TW9cOzjOh_qDBCJP' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=18JYIBOtDfnksZPl4TW9cOzjOh_qDBCJP" -O /tmp/ilm/eval_repro/models/lyr_lmallscratch/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=18Szj-HYwh3sjLmmfF8TNwAmB2oEddool' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=18Szj-HYwh3sjLmmfF8TNwAmB2oEddool" -O /tmp/ilm/eval_repro/data/lyr_sentence_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=18aNMfcqC1wyC8wWJHbCfMxLY49Dbg-du' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=18aNMfcqC1wyC8wWJHbCfMxLY49Dbg-du" -O /tmp/ilm/eval_repro/data/abs_sentence_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1BSIFfuSTznmHIKa4R-AnwIxN93b1Ap-b' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1BSIFfuSTznmHIKa4R-AnwIxN93b1Ap-b" -O /tmp/ilm/eval_repro/models/abs_lm/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1FBY9DR60WWX05orILaFHuyZYlB4ChTpS' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1FBY9DR60WWX05orILaFHuyZYlB4ChTpS" -O /tmp/ilm/eval_repro/models/abs_ilm/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1FGEL3CGzLvnWpgvUYWsHsOUgW65DVxgw' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1FGEL3CGzLvnWpgvUYWsHsOUgW65DVxgw" -O /tmp/ilm/eval_repro/data/lyr_mixture_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1FJBgz26lZPcanZTEf0iWxZCXIEM6esu6' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1FJBgz26lZPcanZTEf0iWxZCXIEM6esu6" -O /tmp/ilm/eval_repro/models/lyr_lm/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1HeuxA2A6iEs6SW26jlCom3x_tFQHnIGu' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1HeuxA2A6iEs6SW26jlCom3x_tFQHnIGu" -O /tmp/ilm/eval_repro/models/abs_lmrevscratch/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1JJyh7clJjyPF-rm4rHFLyX7Y-l_doD0K' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1JJyh7clJjyPF-rm4rHFLyX7Y-l_doD0K" -O /tmp/ilm/eval_repro/data/abs_ngram_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1JzDRUSWVeyGnNaWKVYM8t1BPAs58t6uB' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1JzDRUSWVeyGnNaWKVYM8t1BPAs58t6uB" -O /tmp/ilm/eval_repro/models/lyr_lmscratch/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1KNvdzn1xhpw0Xdh0pMWN3CtrDKEK8d4N' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1KNvdzn1xhpw0Xdh0pMWN3CtrDKEK8d4N" -O /tmp/ilm/eval_repro/data/lyr_document_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Kkli5Brmc3D6qE0b5ww5daZdZroaN1YB' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Kkli5Brmc3D6qE0b5ww5daZdZroaN1YB" -O /tmp/ilm/eval_repro/models/lyr_lmrevscratch/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1LxlyPqz3OvAZsYRRC8yRdSoaCKGB0Ucg' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1LxlyPqz3OvAZsYRRC8yRdSoaCKGB0Ucg" -O /tmp/ilm/train_repro/data/sto_train.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1MBM96hfN2cGJidG-mi_4bE0K07xgWAxT' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1MBM96hfN2cGJidG-mi_4bE0K07xgWAxT" -O /tmp/ilm/eval_repro/data/sto_paragraph_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1PdVg-TnG5VQt8GCQOQA841AGw1GR44yl' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1PdVg-TnG5VQt8GCQOQA841AGw1GR44yl" -O /tmp/ilm/eval_repro/data/abs_word_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Qy13Dw60Jd5HqN89q8WvCMtwvTXJw7tj' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Qy13Dw60Jd5HqN89q8WvCMtwvTXJw7tj" -O /tmp/ilm/eval_repro/models/sto_lmallscratch/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1RObPpSttNtMw4UQ1bGiVzEM-94QqkwHT' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1RObPpSttNtMw4UQ1bGiVzEM-94QqkwHT" -O /tmp/ilm/eval_repro/models/lyr_ilmscratch/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1TA3ySrvcWxaNtoDPpN8Jk7uqjGKdPqda' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1TA3ySrvcWxaNtoDPpN8Jk7uqjGKdPqda" -O /tmp/ilm/eval_repro/data/abs_mixture_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Td-yr6g5cTxW4yoz_Wv4gSi-wbu1376R' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Td-yr6g5cTxW4yoz_Wv4gSi-wbu1376R" -O /tmp/ilm/eval_repro/data/lyr_word_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1UjPh51URE8hvK-yTw3xkVwkBwEcCo6Uz' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1UjPh51URE8hvK-yTw3xkVwkBwEcCo6Uz" -O /tmp/ilm/eval_repro/data/abs_document_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1XAug1jhm7sa5lksDV6GMyF8sFQLwk1Y6' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1XAug1jhm7sa5lksDV6GMyF8sFQLwk1Y6" -O /tmp/ilm/eval_repro/models/lyr_lmrev/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1XU61GMduqJeCzYqDk8BQ7S4M8tbzqF9g' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1XU61GMduqJeCzYqDk8BQ7S4M8tbzqF9g" -O /tmp/ilm/eval_repro/models/abs_lmallscratch/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Y4HRYrBnqwtdbziF5Q6b5WaIFxJd1v7m' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Y4HRYrBnqwtdbziF5Q6b5WaIFxJd1v7m" -O /tmp/ilm/train_repro/data/sto_valid.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1ZTZOO5fVTlnPBw7EC_4OOEzHmcs6tAFO' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1ZTZOO5fVTlnPBw7EC_4OOEzHmcs6tAFO" -O /tmp/ilm/eval_repro/models/abs_ilmscratch/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Zsuj8Plrcs49f-5rV6dvJ5W2kIz_C30u' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Zsuj8Plrcs49f-5rV6dvJ5W2kIz_C30u" -O /tmp/ilm/eval_repro/data/sto_mixture_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1_uCgugc57tPGfFofKbU8doJN23cf4lEY' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1_uCgugc57tPGfFofKbU8doJN23cf4lEY" -O /tmp/ilm/eval_repro/models/sto_lmrev/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1dPOLkggPbe-Pzn8VVkcrinuGJv2yRieR' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1dPOLkggPbe-Pzn8VVkcrinuGJv2yRieR" -O /tmp/ilm/eval_repro/models/sto_lmall/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1dbCCc68TvY6segwTrrxYS1ukVbdC7zgJ' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1dbCCc68TvY6segwTrrxYS1ukVbdC7zgJ" -O /tmp/ilm/eval_repro/data/lyr_ngram_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1hHdXX43qkkm-zpUCJz_iuv1vRRpyfbaP' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1hHdXX43qkkm-zpUCJz_iuv1vRRpyfbaP" -O /tmp/ilm/train_repro/data/abs_valid.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1jGCjboxlFUF0jqvB0_-L0eeylhKWfZJV' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1jGCjboxlFUF0jqvB0_-L0eeylhKWfZJV" -O /tmp/ilm/train_repro/data/lyr_train.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1nYuYCS5fDP2_vB7A92guk0PWh5CC2I5x' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1nYuYCS5fDP2_vB7A92guk0PWh5CC2I5x" -O /tmp/ilm/eval_repro/models/lyr_ilm/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1nrNkd4cBsdZS0eajA3wD1i5b6t6R6bow' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1nrNkd4cBsdZS0eajA3wD1i5b6t6R6bow" -O /tmp/ilm/eval_repro/models/lyr_lmall/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1oYFLxkX6mWbmpEwQH8BmgE7iKix2W0zU' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1oYFLxkX6mWbmpEwQH8BmgE7iKix2W0zU" -O /tmp/ilm/eval_repro/models/sto_ilm/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1qyM0OCL8pI5dL7sfAag-y9X_bnlTS_1Z' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1qyM0OCL8pI5dL7sfAag-y9X_bnlTS_1Z" -O /tmp/ilm/eval_repro/models/abs_lmall/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1rw45GKP4iRJLzXnRtX-rnk_NeGXOqWkU' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1rw45GKP4iRJLzXnRtX-rnk_NeGXOqWkU" -O /tmp/ilm/train_repro/data/abs_train.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1vGxdfZUWtOB5ajpDgSGUXuHK5_BGY9GA' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1vGxdfZUWtOB5ajpDgSGUXuHK5_BGY9GA" -O /tmp/ilm/eval_repro/models/sto_lmscratch/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1w02hGewoBk_Pq-thrtbOcU1JPGRdGL_U' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1w02hGewoBk_Pq-thrtbOcU1JPGRdGL_U" -O /tmp/ilm/eval_repro/data/sto_sentence_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1x8RBys_jbreSFO1zMdmwiT2ref2F8q_C' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1x8RBys_jbreSFO1zMdmwiT2ref2F8q_C" -O /tmp/ilm/eval_repro/data/sto_ngram_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1xR0LC5WHV1UQDPjWTN0HcOQ9C5jsXYef' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1xR0LC5WHV1UQDPjWTN0HcOQ9C5jsXYef" -O /tmp/ilm/train_repro/data/lyr_valid.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1xXJfjCNzRLXYZgHgUrNimP4CtUW0Ziph' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1xXJfjCNzRLXYZgHgUrNimP4CtUW0Ziph" -O /tmp/ilm/eval_repro/data/abs_paragraph_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1xbyQ5bMJpTxlsPtL1YsH2jmUUh_49gOI' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1xbyQ5bMJpTxlsPtL1YsH2jmUUh_49gOI" -O /tmp/ilm/eval_repro/models/sto_lmrevscratch/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1ydEjL0SMbX8p-1w6XeLWNrzeVn8TleGT' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1ydEjL0SMbX8p-1w6XeLWNrzeVn8TleGT" -O /tmp/ilm/eval_repro/data/sto_document_test.pkl && rm -rf /tmp/cookies.txt
RUN wget -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1yl36oZq9R_d3IhlFWLlMGq46n8F9Lq1q' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1yl36oZq9R_d3IhlFWLlMGq46n8F9Lq1q" -O /tmp/ilm/eval_repro/models/abs_lmrev/pytorch_model.bin && rm -rf /tmp/cookies.txt
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/abs_ilm/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/abs_ilmscratch/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/abs_lm/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/abs_lmall/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/abs_lmallscratch/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/abs_lmrev/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/abs_lmrevscratch/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/abs_lmscratch/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/lyr_ilm/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/lyr_ilmscratch/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/lyr_lm/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/lyr_lmall/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/lyr_lmallscratch/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/lyr_lmrev/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/lyr_lmrevscratch/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/lyr_lmscratch/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/sto_ilm/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/sto_ilmscratch/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/sto_lm/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/sto_lmall/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/sto_lmallscratch/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/sto_lmrev/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/sto_lmrevscratch/config.json
RUN wget -nc --no-check-certificate 'https://docs.google.com/uc?export=download&id=15JnXi7L6LeEB2fq4dFK2WRvDKyX46hVi' -O /tmp/ilm/eval_repro/models/sto_lmscratch/config.json
